config/routes.rb
Rails.application.routes.draw do
  resources :colds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cold.rb
class Cold < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/colds_controller.rb
class ColdsController < ApplicationController
  before_action :set_cold, only: [:show, :edit, :update, :destroy]

  # GET /colds
  # GET /colds.json
  def index
    @colds = Cold.all
  end

  # GET /colds/1
  # GET /colds/1.json
  def show
  end

  # GET /colds/new
  def new
    @cold = Cold.new
  end

  # GET /colds/1/edit
  def edit
  end

  # POST /colds
  # POST /colds.json
  def create
    @cold = Cold.new(cold_params)

    respond_to do |format|
      if @cold.save
        format.html { redirect_to @cold, notice: 'Cold was successfully created.' }
        format.json { render :show, status: :created, location: @cold }
      else
        format.html { render :new }
        format.json { render json: @cold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colds/1
  # PATCH/PUT /colds/1.json
  def update
    respond_to do |format|
      if @cold.update(cold_params)
        format.html { redirect_to @cold, notice: 'Cold was successfully updated.' }
        format.json { render :show, status: :ok, location: @cold }
      else
        format.html { render :edit }
        format.json { render json: @cold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colds/1
  # DELETE /colds/1.json
  def destroy
    @cold.destroy
    respond_to do |format|
      format.html { redirect_to colds_url, notice: 'Cold was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cold
      @cold = Cold.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cold_params
      params.require(:cold).permit(:choose)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colds_helper.rb
module ColdsHelper
end

app/views/colds/_form.html.erb
<%= form_for(cold) do |f| %>
  <% if cold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cold.errors.count, "error") %> prohibited this cold from being saved:</h2>

      <ul>
      <% cold.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :choose %>
    <%= f.time_select :choose %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colds/edit.html.erb
<h1>Editing Cold</h1>

<%= render 'form', cold: @cold %>

<%= link_to 'Show', @cold %> |
<%= link_to 'Back', colds_path %>

app/views/colds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choose</h1>

<table>
  <thead>
    <tr>
      <th>Choose</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colds.each do |cold| %>
      <tr>
        <td><%= cold.choose %></td>
        <td><%= link_to 'Show', cold %></td>
        <td><%= link_to 'Edit', edit_cold_path(cold) %></td>
        <td><%= link_to 'Destroy', cold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cold', new_cold_path %>

app/views/colds/new.html.erb
<h1>choose</h1>

    <h2>新增讨论版</h2>
    <hr>
    <%= form_for @cold do |f| %>
    标题
    <%= f.time_select :choose,  minute_step: 5, start_hour: 0, end_hour: 23 %>`
    <br>
    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end %>

<%= link_to 'Back', colds_path %>

app/views/colds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Choose:</strong>
  <%= @cold.choose %>
</p>

<%= link_to 'Edit', edit_cold_path(@cold) %> |
<%= link_to 'Back', colds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiim</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>